### PR TITLE
Update CPS 1/1.5/2

### PR DESCRIPTION
**Pull request by atrac17**
If approved, I will update jtbin accordingly for CPS 1.5 mra files. 

Information taken from service manuals. Complete release for CPS Dash hardware.

- Fixed `machinename wofr1` from mame, this was previously unplayable due to CPS B Board configuration
- Updated cps1.cpp mra files to mame 0.229 or higher for CPS 1.5
- Added B Board configuration per machine name where applicable
- No bootlegs
- Buttons labeled
- Metadata updated
- Manuals added to repository for reference

Notes:

- grego2d ports will be added in the future with patched mra files
- CPS 1 and CPS 2 will also be submitted in separate pull requests shortly
- I will update this repository to current format (toml) for mra files in the future after completing a refresh of what is currently available in jtbin

### CODE REVIEW

**Comment by atrac17** [comment]
If approved, I will update jtbin accordingly for CPS 1 mra files.

Information taken from service manuals. Complete release for CPS 1 hardware.

- Updated cps1.cpp mra files to mame 0.229 or higher for CPS 1
- New clones available not in jtbin
- Added B Board configuration per machine name where applicable
- No bootlegs (machinename sf2/sf2ce bootlegs will be added in a separate pull request with separate script)
- Buttons labeled
- Metadata updated
- Manuals added to repository for reference (more manuals to be added in the future)

Notes:

- Carrier Air Wing priority fix is available from a different mapper (will discuss offline)

- Information taken from https://github.com/mamedev/mame/blob/master/src/mame/video/cps1.cpp.

- Some mapping information may not match the cps1.cpp and is sourced from jtbin (two mappers would not take from mame).

- The ghouls.xml has ghost oki region. Additional mapping for the leftover single rom was manually applied to machinames [ghouls] and [ghoulsu]. This includes a cheat mra and patched mra for machinename ghouls to skip the rom check.

- The nemo.xml displays correctly with mapping provided from cps1.cpp still.

- I have added nvram for pang3 and all other machine names from the cps1.cpp for future highscore save support by jimmystones when jtframe is updated in the future.

- The forgottn.xml gfx roms were edited manually for the following machinenames [forgottn], [forgottnu], and [forgottna].


forgottn gfx:

```
        <interleave output="64">
            <part name="lw_2.2b" crc="4bd75fee" map="00000001"/>
            <part name="lw_1.2a" crc="65f41485" map="00000010"/>
            <part name="lw-08.9b" crc="25a8e43c" map="00002100" length="0x40000" offset="0"/>
            <part name="lw_18.5e" crc="b4b6241b" map="00010000"/>
            <part name="lw_17.5c" crc="c5eea115" map="00100000"/>
            <part name="lw_30.8h" crc="b385954e" map="01000000"/>
            <part name="lw_29.8f" crc="7bda1ac6" map="10000000"/>
        </interleave>
        <interleave output="64">
            <part name="lw_4.3b" crc="50cf757f" map="00000001"/>
            <part name="lw_3.3a" crc="c03ef278" map="00000010"/>
            <part name="lw-08.9b" crc="25a8e43c" map="00002100" length="0x40000" offset="0x40000"/>
            <part name="lw_20.7e" crc="df1a3665" map="00010000"/>
            <part name="lw_19.7c" crc="15af8440" map="00100000"/>
            <part name="lw_32.9h" crc="30967a15" map="01000000"/>
            <part name="lw_31.9f" crc="c49d37fb" map="10000000"/>
        </interleave>
        <interleave output="64">
            <part name="lw-02.6b" crc="43e6c5c8" map="00000021" length="0x40000" offset="0"/>
            <part name="lw_14.10b" crc="82862cce" map="00000100"/>
            <part name="lw_13.10a" crc="b81c0e96" map="00001000"/>
            <part name="lw-06.9d" crc="5b9edffc" map="00210000" length="0x40000" offset="0"/>
            <part name="lw_26.10e" crc="57bcd032" map="01000000"/>
            <part name="lw_25.10c" crc="bac91554" map="10000000"/>
        </interleave>
        <interleave output="64">
            <part name="lw-02.6b" crc="43e6c5c8" map="00000021" length="0x40000" offset="0x40000"/>
            <part name="lw_16.11b" crc="40b26554" map="00000100"/>
            <part name="lw_15.11a" crc="1b7d2e07" map="00001000"/>
            <part name="lw-06.9d" crc="5b9edffc" map="00210000" length="0x40000" offset="0x40000"/>
            <part name="lw_28.11e" crc="a805ad30" map="01000000"/>
            <part name="lw_27.11c" crc="103c1bd2" map="10000000"/>
        </interleave>
```

The pang3.xml gfx roms were edited manually and dipswitches added manually for proper bootup to game and not service menu.

pang3 gfx rom example:

```
        <interleave output="64">
            <part name="pa3-01m.2c" crc="068a152c" map="00000021" length="0x100000" offset="0"/>
            <part name="pa3-07m.2f" crc="3a4a619d" map="00002100" length="0x100000" offset="0"/>
            <part name="pa3-01m.2c" crc="068a152c" map="00210000" length="0x100000" offset="0x100000"/>
            <part name="pa3-07m.2f" crc="3a4a619d" map="21000000" length="0x100000" offset="0x100000"/>
        </interleave>
```

**Comment by atrac17** [comment]
@jotego this is ready for review. I have tested all 436 mra files. When future clones are added to mame (when found), I will update the scripts and mra's here in a pull request.

**Comment by jotego** [comment]
The source code repositories have development as the main target, not file distribution. This is quite a disruptive commit with over one thousand files modified. It is a lot to review. It would have been easier to make two or three PR for intermediate steps instead of a single large one.

I see things that look positive, like the way the NVRAM files are included in the MRA. But some changes like the folder structure (including duplicating files such as catver.ini) affect the way this repository is organized in comparison with other projects. All projects have the XML files in the **rom** folder, together with other files that are not committed, and then a single mra folder there **rom/mra** for all the systems in the repository. The scripts for generating the MRA files are in the **rom** folder too.

The manuals are supposed to be in the **doc** folder, and not under **rom**. I have mixed feelings about adding manuals as they could be used as an excuse for shutting down the repository for copyright infringement. I used to add many manuals but nowadays I tend to add only schematics and have even started deleting manuals from the jt_gng repository.

If you keep the folder structure, it is easier to see the differences in commits. I cannot easily see the changes in the MRA files with the merge tool as it is now.

Anyway, it looks like a positive change but it is massive and hard to review. The thing I need is to go back to the old folder structure. Let me look at the new and modified files with the old structure, merge that change and then we can discuss whether we make folder changes. NVRAM files can go under **rom/nvram**

**Comment by atrac17** [comment]
I'll close this and start over.

**Pull request closed without merging**
